apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerCluster
metadata:
  name: "${CLUSTER_NAME}"
spec:
  hcloudNetwork:
    enabled: false
  controlPlaneRegions:
    - "${HCLOUD_REGION}"
  controlPlaneEndpoint:
    host: ""
    port: 443
  controlPlaneLoadBalancer:
    region: "${HCLOUD_REGION}"
  hcloudPlacementGroups:
    - name: control-plane
      type: spread
    - name: md-0
      type: spread
  sshKeys:
    hcloud:
      - name: "${HCLOUD_SSH_KEY}"
  hetznerSecretRef:
    name: hetzner
    key:
      hcloudToken: hcloud
