apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: TalosControlPlane
metadata:
  name: ${CLUSTER_NAME}-control-plane
spec:
  replicas: ${CONTROL_PLANE_MACHINE_COUNT}
  version: ${KUBERNETES_VERSION}
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: v0.14
      configPatches:
        - op: add
          path: /cluster/externalCloudProvider
          value:
            enabled: true
  infrastructureTemplate:
    kind: HCloudMachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    name: "${CLUSTER_NAME}-control-plane"
