apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerBareMetalMachineTemplate
metadata:
  name: "${CLUSTER_NAME}-md-1"
spec:
  template:
    spec:
      installImage:
        image:
          path: /root/.oldroot/nfs/install/../images/Ubuntu-2004-focal-64-minimal-hwe.tar.gz
        partitions:
          - mount: /boot
            fileSystem: ext4
            size: 1024M
          - mount: /
            fileSystem: ext4
            size: all
        postInstallScript: |
          #!/bin/bash
          apt-get update && apt-get install -y cloud-init apparmor apparmor-utils
      sshSpec:
        portAfterInstallImage: 22
        portAfterCloudInit: 22
        secretRef:
          name: robot-ssh
          key:
            name: sshkey-name
            publicKey: ssh-publickey
            privateKey: ssh-privatekey
