apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: TalosConfigTemplate
metadata:
  name: "${CLUSTER_NAME}-md-0"
spec:
  template:
    spec:
      generateType: worker
      talosVersion: v0.14
      configPatches:
        - op: add
          path: /cluster/externalCloudProvider
          value:
            enabled: true
