name: "Metadata"
description: "Generate Image Metadata"
inputs:
  metadata_flavor:
    description: "metadata_flavor"
    required: true
  metadata_tags:
    description: "metadata_tags"
    required: true
outputs:
  tags:
    description: "generated image tags"
    value: ${{ steps.meta.outputs.tags }}
  labels:
    description: "generated image labels"
    value: ${{ steps.meta.outputs.labels }}
  version:
    description: "generated image version"
    value: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
runs:
  using: "composite"
  steps:
    - name: Docker manager metadata
      id: meta
      uses: docker/metadata-action@31cebacef4805868f9ce9a0cb03ee36c32df2ac4 # v5.3.0
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        flavor: ${{ inputs.metadata_flavor }}
        tags: ${{ inputs.metadata_tags }}
