name: "Setup Go"
description: "Setup Go"
inputs:
  version:
    description: "Go Version to setup"
    required: true
    default: "1.19"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3
      with:
        go-version: ${{ inputs.version }}
    - id: go-cache-paths
      shell: bash
      run: |
        echo "::set-output name=go-build::$(go env GOCACHE)"
        echo "::set-output name=go-mod::$(go env GOMODCACHE)"
    - name: Go Mod Cache
      uses: actions/cache@69d9d449aced6a2ede0bc19182fadc3a0a42d2b0 # v3
      with:
        path: ${{ steps.go-cache-paths.outputs.go-mod }}
        key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mod-
    - name: Go Build Cache
      uses: actions/cache@69d9d449aced6a2ede0bc19182fadc3a0a42d2b0 # v3
      with:
        path: ${{ steps.go-cache-paths.outputs.go-build }}
        key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-build-
