name: "Manager Image"
description: "Build and Push Manager Image"
inputs:
  manager_image_quay_username:
    description: "manager_image_quay_username"
    required: true
  manager_image_quay_password:
    description: "manager_image_quay_password"
    required: true
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-go
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f03ac48505955848960e80bbb68046aa35c7b9e7 # v2

    - name: Generate metadata
      id: meta
      uses: ./.github/actions/metadata
      with:
        quay_username: ${{ inputs.manager_image_quay_username }}
        metadata_flavor: ${{ env.metadata_flavor }}
        metadata_tags: ${{ env.metadata_tags }}

    - name: Log into quay.io
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2
      env:
        QUAY_USERNAME: ${{ inputs.manager_image_quay_username }}
      if: ${{ env.QUAY_USERNAME != '' }}
      with:
        registry: quay.io
        username: ${{ inputs.manager_image_quay_username }}
        password: ${{ inputs.manager_image_quay_password }}

    - name: Build and push manager image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64
        cache-from: type=gha, scope=${{ github.workflow }}
        cache-to: type=gha, mode=max, scope=${{ github.workflow }}
