name: E2E Baremetal Feature
on:
  workflow_dispatch:
env:
  hcloudctl_version: 1.30.3
  IMAGE_NAME: cluster-api-provider-hetzner
  REGISTRY: quay.io/syself
  metadata_flavor: latest=false
  metadata_tags: type=sha

jobs:
  manager-image:
    name: Build and push manager image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Build and push manager image
        id: manager-image
        uses: ./.github/actions/manager-image
        with:
          manager_image_quay_username: ${{ secrets.QUAY_USERNAME }}
          manager_image_quay_password: ${{ secrets.QUAY_PASSWORD }}

  test-release:
    name: Test Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Test Release
        id: manager-image
        uses: ./.github/actions/test-release
        with:
          test_release_quay_username: ${{ secrets.QUAY_USERNAME }}

  e2e-hetzner-baremetal-feature:
    name: Test Hetzner Baremetal Features
    concurrency: ci-${{ github.ref }}-e2e-baremetal-hetzner
    runs-on: ubuntu-latest
    needs:
      - manager-image
      - test-release
    steps:
      - name: checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Run e2e Test
        id: e2e
        uses: ./.github/actions/e2e
        with:
          e2e_name: hetzner-baremetal-feature
          e2e_make_target: test-e2e-baremetal-feature
          e2e_quay_username: ${{ secrets.QUAY_USERNAME }}
          e2e_tts_token: ${{ secrets.TTS_TOKEN }}
          e2e_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          e2e_robot_user: ${{ secrets.HETZNER_ROBOT_USER }}
          e2e_robot_password: ${{ secrets.HETZNER_ROBOT_PASSWORD }}
          e2e_ssh_pub: ${{ secrets.HETZNER_SSH_PUB }}
          e2e_ssh_priv: ${{ secrets.HETZNER_SSH_PRIV }}
