name: E2E Feature
on:
  workflow_dispatch:
env:
  IMAGE_NAME: caph-staging
  REGISTRY: ghcr.io/syself
  metadata_flavor: latest=false
  metadata_tags: type=sha

jobs:
  manager-image:
    name: Build and push manager image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Build and push manager image
        id: manager-image
        uses: ./.github/actions/manager-image

  test-release:
    name: Test Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Test Release
        id: manager-image
        uses: ./.github/actions/test-release

  e2e-hcloud-feature:
    name: Test Hcloud Features
    concurrency: ci-${{ github.ref }}-e2e-feature
    runs-on: ubuntu-latest
    needs:
      - manager-image
      - test-release
    steps:
      - name: checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Run e2e Test
        id: e2e
        uses: ./.github/actions/e2e
        with:
          e2e_name: hcloud-feature
          e2e_make_target: test-e2e-feature
          e2e_tts_token: ${{ secrets.TTS_TOKEN }}
          e2e_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
