---
name: Labels

on: # yamllint disable-line rule:truthy
  pull_request_target:
    branches:
      - main

jobs:
  labels:
    name: Labels
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3

      - name: Generate Token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1
        id: generate-token
        with:
          app_id: ${{ secrets.SYSELF_APP_ID }}
          private_key: ${{ secrets.SYSELF_APP_PRIVATE_KEY }}

      - name: Generate Size
        uses: pascalgn/size-label-action@1619680c5ac1ef360b944bb56a57587ba4aa2af8 # v0.4.3
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          sizes: >
            {
              "0": "XS",
              "20": "S",
              "50": "M",
              "200": "L",
              "800": "XL",
              "2000": "XXL"
            }
      - name: Generate Labels
        uses: actions/labeler@5c7539237e04b714afd8ad9b4aed733815b9fab4 # v4
        with:
          configuration-path: .github/labeler.yaml
          repo-token: ${{ steps.generate-token.outputs.token }}

      - name: Sync Labels
        uses: EndBug/label-sync@da00f2c11fdb78e4fae44adac2fdd713778ea3e8 # v2
        with:
          config-file: .github/labels.yaml
          token: ${{ steps.generate-token.outputs.token }}
