name: E2E PR Blocking
on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
      - "releases/**"
    paths:
      - "**.go"
      - "**go.mod"
      - "**go.sum"
      - "<templates|test>/**/*.<yml|yaml>"
      - ".github/actions/**/*"
      - ".github/workflows/e2e-*"
      - ".github/workflows/pr-*"
      - "!**/vendor/**"
env:
  IMAGE_NAME: caph-staging
  REGISTRY: ghcr.io/syself
  metadata_flavor: latest=false
  metadata_tags: type=ref,event=pr

jobs:
  manager-image:
    name: Build and push manager image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Build and push manager image
        id: manager-image
        uses: ./.github/actions/manager-image

  test-release:
    name: Test Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Test Release
        id: manager-image
        uses: ./.github/actions/test-release

  e2e-hcloud-basic:
    name: Test Hcloud Basic
    concurrency: ci-${{ github.ref }}-e2e-basic
    runs-on: ubuntu-latest
    needs:
      - manager-image
      - test-release
    steps:
      - name: checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Run e2e Test
        id: e2e
        uses: ./.github/actions/e2e
        with:
          e2e_name: hcloud-basic
          e2e_make_target: test-e2e
          e2e_tts_token: ${{ secrets.TTS_TOKEN }}
          e2e_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}

  e2e-hetzner-basic:
    name: Test Hetzner Baremetal Basic
    concurrency: ci-${{ github.ref }}-e2e-basic-hetzner
    runs-on: ubuntu-latest
    needs:
      - manager-image
      - test-release
    steps:
      - name: checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Run e2e Test
        id: e2e-bm
        uses: ./.github/actions/e2e
        with:
          e2e_name: hetzner-basic
          e2e_make_target: test-e2e-baremetal
          e2e_tts_token: ${{ secrets.TTS_TOKEN }}
          e2e_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          e2e_robot_user: ${{ secrets.HETZNER_ROBOT_USER }}
          e2e_robot_password: ${{ secrets.HETZNER_ROBOT_PASSWORD }}
          e2e_ssh_pub: ${{ secrets.HETZNER_SSH_PUB }}
          e2e_ssh_priv: ${{ secrets.HETZNER_SSH_PRIV }}
