name: starlark
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - "**Tiltfile"
jobs:
  starlark:
    name: run starlark lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: run starlark lint
        run: make verify-tiltfile
