name: Verify PR Code
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - "releases/**"
    paths-ignore:
      - "**.md"

jobs:
  test:
    name: Verify Code
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Install go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3
        with:
          go-version: "^1.19"
      - name: Verify Boilerplate
        run: make verify-boilerplate
      - name: Verify Modules
        run: make verify-modules
      - name: Verify gen
        run: make verify-gen
